___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [10]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [11]:
np.__version__


'1.18.5'

In [12]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']


Створити вектор з 10 елементів, заповнений одиницями:

In [13]:
Z = np.ones(10)
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Створити вектор із значеннями від 0 до 10:

In [14]:
Z = np.arange(0,11)
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10]


Створити матрицю 5 на 5, заповнену нулями:

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [16]:
Z = np.random.randint(20, size=20)
print(Z)
print(np.nonzero(Z))

[ 5  6 13 12 10 16 11 10  3  0  3 11  4 13 18 15 11  8  6 13]
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19]),)


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [17]:
print("Среднее значение:", Z.mean())
print("Медиана:", np.median(Z))
print("Стандартное отклонение:", np.std(Z))


Среднее значение: 9.4
Медиана: 10.5
Стандартное отклонение: 4.726520919238589


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [18]:
M1 = np.random.randint(10, size=(4,2))
M2 = np.random.randint(10, size=(2,2))
Z = np.dot(M1, M2)

print('Матрица 1:')
print(M1)
print('Матрица 2:')
print(M2)
print('Произведение матриц:')
print(Z)

Матрица 1:
[[8 1]
 [4 9]
 [9 9]
 [5 4]]
Матрица 2:
[[8 4]
 [8 3]]
Произведение матриц:
[[ 72  35]
 [104  43]
 [144  63]
 [ 72  32]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [19]:
V = np.reshape(Z,(1,Z.size))
print('Преобразование матрицы в вектор:')
print(V)

Vmin, Vmax = V.min(), V.max()
print('Max значение:', Vmax)
print('Min значение:', Vmin)

V[V==Vmax]=0
print('Матрица где Max значение заменить на 0:')
print(V)

Преобразование матрицы в вектор:
[[ 72  35 104  43 144  63  72  32]]
Max значение: 144
Min значение: 32
Матрица где Max значение заменить на 0:
[[ 72  35 104  43   0  63  72  32]]


Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [20]:
cor_1 = np.corrcoef(Z)[0, 1]
cor_2 = np.corrcoef(Z)[0, 2]
cor_3 = np.corrcoef(Z)[0, 3]

print("Матрица:")
print(Z)
print(cor_1, '- корреляция строки 1 со строкой 2')
print(cor_2, '- корреляция строки 1 со строкой 3')
print(cor_3, '- корреляция строки 1 со строкой 4')

Матрица:
[[ 72  35]
 [104  43]
 [  0  63]
 [ 72  32]]
1.0 - корреляция строки 1 со строкой 2
-1.0 - корреляция строки 1 со строкой 3
0.9999999999999999 - корреляция строки 1 со строкой 4


Дано матрицю. Знайти ранг матриці:

In [21]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

print(np.linalg.matrix_rank(a))


3


Знайти визначник матриці:

In [22]:
print(np.linalg.det(a))

440.0000000000002


Знайти власні значення та власні вектори матриці: 

In [23]:
w,v = np.linalg.eig(a)

print(w)
print(v)

[14.13520334+0.j         -4.56760167+3.20389947j -4.56760167-3.20389947j]
[[ 0.43131913+0.j         -0.31386258-0.47450898j -0.31386258+0.47450898j]
 [ 0.41502436+0.j         -0.07049527+0.4090732j  -0.07049527-0.4090732j ]
 [ 0.8010734 +0.j          0.7099444 +0.j          0.7099444 -0.j        ]]


Знайдіть число, що найчастіше зустрічається в масиві:

In [24]:
a = np.random.randint(0,10,50)
print(a)
counts = np.bincount(a)
print (np.argmax(counts))

[3 5 7 1 8 5 8 9 5 4 1 3 5 2 7 3 4 9 8 3 4 3 4 2 0 7 8 1 0 3 0 9 5 6 7 9 8
 3 1 0 0 4 3 9 6 5 4 8 7 7]
3


Виведіть лише парні числа, що діляться на 5:

In [47]:
import numpy as np
a = np.random.randint(0,11,50)

print(a)

b = [x for x in a if (x % 2 == 0) & (x % 5 == 0) & (x != 0)]

if len(b)==0:
    print('таких чисел нет')
else:
    print(b)
        




[ 5  2  5  1  2  3  0  6  6  9  2  7  1 10 10  9  3  7  2  4  6  7  9 10
  2  9  5  7  5  2  9  7  6  0  6  9  9  1  9  9  9  5  5  7  2  4  0  0
  9  9]
[10, 10, 10]


Розв'яжіть систему рівнянь:
![](https://render.githubusercontent.com/render/math?math=2x%20%2B%205y%20%3D%201&mode=display)
![](https://render.githubusercontent.com/render/math?math=x%20-%2010y%20%3D%203&mode=display)

In [48]:
M1 = np.array([[2, 5],[1, -10]])
V1 = np.array([1,3])

print(np.linalg.solve(M1,V1))

[ 1.  -0.2]
